meta_product_name: "Epicenter"
meta_title: "Epicenter - Meet in the middle"
meta_description: "Create an event without a location. Share with friends who tell us where they're coming from. We find the central point and recommend a nearby bar or cafe."
meta_image: "largelogo.png"
